### ISSUE TITLE
Avoid using reserved identifier of Camlp4 extensions

### ISSUE THREAD

**Issue by objmagic** [pyrocat101/opal#1]
`parser` is a keyword of Camlp4 extension, and core library uses Camlp4. When using this library and core together, error will show up.

**Comment by pyrocat101** [comment]
Could you make a pull request?

**Comment by objmagic** [comment]
Simply changing the keyword `parser` to other name is not enough. Some other incompatibility error will show up because of the use of `>>`, etc.

I suggest one should not add camlp4 flag when compiling.
