### ISSUE TITLE
OPAM package?

### ISSUE THREAD

**Issue by nv-vn** [pyrocat101/opal#2]
Hi pyrocat! I noticed that Opal doesn't currently have a package available on OPAM. Since this seems like a pretty useful library, I think that you should create a package for it on OPAM to make installation more convenient. Do you have any interest in doing this/any reasons that you don't wanna do it? Either way, keep up the good work!

**Comment by pyrocat101** [comment]
Closed by https://github.com/ocaml/opam-repository/pull/6215
