### ISSUE TITLE
chainr should be like chainl

### ISSUE THREAD

**Issue by magv** [pyrocat101/opal#3]
Hi. As of v0.1.0, the type for `chainl1` is:

```
('a -> ('b * 'c) option) -> ('c -> (('b -> 'b -> 'b) * 'a) option) -> 'a -> ('b * 'c) option
```

... while the type for `chainr1` is:

```
('a -> ('b * 'c) option) -> ('c -> (('b -> 'b -> 'c -> ('b * 'c) option) * 'a) option) -> 'a -> ('b * 'c) option
```

This discrepancy is fairly surprising, since the docs say these two are pretty much the same things, aside from the order of application.

To cut the story short, I think the definition of `chainr1` should be changed from this:

``` ocaml
let rec chainr1 x op =
  x >>= fun a -> (op >>= fun f -> chainr1 x op >>= f a) <|> return a
```

... into something more like this:

``` ocaml
let rec chainr1 x op =
 x >>= fun a -> (op >>= fun f -> chainr1 x op >>= fun b -> return (f a b)) <|> return a
```

**Comment by magv** [comment]
... or better yet, like this:

``` ocaml
let rec chainr1 x op =
 x >>= fun a -> (op >>= fun f -> chainr1 x op => f a) <|> return a
```

**Comment by pyrocat101** [comment]
Good catch :)
